#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'thor'


class DAS < Thor

  URL = "https://www.destroyallsoftware.com/screencasts/feed"

  desc "Search <Regex>", "search destroyallsoftware"
  def search(regex)
    fetch_title_each do |t|
      puts t if t.match regex
    end
  end

  desc "List", "list all videos"
  def list
    fetch_title_each do |item|
      puts item 
    end
  end
  

  private

  def fetch_title_each
    doc = Nokogiri::XML(open(URL))
    items = doc.root.xpath("channel/item/title")
    items.map { |t| yield t.text }
  end

  # def download_feed
  #   uri = URI.parse("https://www.destroyallsoftware.com/screencasts/feed")
  #   http = Net::HTTP.new(uri.host, uri.port)
  #   http.use_ssl = true
  #   http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  #   request = Net::HTTP::Get.new(uri.request_uri)

  #   response = http.request(request)
  #   response.body
  # end

end

DAS.start(ARGV)
